name: Release CI

on:
  push:
    tags:
      - v*

permissions: 
  write-all
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: |
          nr build
          nr generate:file
          cp activator.conf dist/activator.conf

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: activation-script-dist.zip
          path: dist
      - name: Zip
        run: zip -r activation-script-dist.zip dist
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: activation-script-dist.zip
          path: activation-script-dist.zip

      - name: Create Release
        id: create_release
        run: |
          npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: activation-script-dist.zip
          asset_name: activation-script-dist.zip
          asset_content_type: application/zip